// GENERATED by scripts/build-editor.mjs from nocms.config.mjs — do not edit.
import r0 from "@astrojs/react/server.js";

export const renderers = [
  { name: "@astrojs/react", server: r0, client: "@astrojs/react/client.js" },
];
