import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { build } from "vite";
import astroForEditor from "./astro-plugin.mjs";
import { declaredFrameworks, shimPlugin } from "./renderer-shims.mjs";

/**
 * The renderer list is generated, never hand-written: adding a component library that
 * needs a new framework is a line in nocms.config.mjs, not a core change.
 *
 * ORDER IS LOAD-BEARING. React's check() reads Component["$$typeof"] and throws on
 * foreign object components, so object-based frameworks claim theirs first.
 */
const ORDER = ["vue", "svelte", "solid", "preact", "react"];

const STYLES_ID = "/@nocms/styles";

/**
 * Global stylesheets reach the built page through Astro, but an SSR build strips CSS
 * imports — so a library's stylesheet would silently never reach the canvas, and its
 * components would render unstyled in the editor while the site looked correct.
 * This inlines the declared stylesheets as text for the editor to inject.
 */
function declaredStyles(rootDir) {
  return {
    name: "nocms-declared-styles",
    resolveId: (id) => (id === STYLES_ID ? `\0${STYLES_ID}` : null),
    async load(id) {
      if (id !== `\0${STYLES_ID}`) return null;
      const files = config.default.styles ?? [];
      const sheets = await Promise.all(
        files.map(async (file) => {
          // Either a project path ("src/styles/app.css") or a package one
          // ("daisyui/daisyui.css"); try the project first.
          const tried = [
            new URL(file.replace(/^\.\//, ""), `file://${rootDir}`),
            new URL(`node_modules/${file}`, `file://${rootDir}`),
          ];
          for (const candidate of tried) {
            try {
              return await readFile(candidate, "utf-8");
            } catch {
              /* try the next candidate */
            }
          }
          // A missing stylesheet must fail loudly at build time, not silently in the
          // canvas — that is exactly the parity break this exists to prevent.
          throw new Error(
            `nocms.config styles: cannot read "${file}" (tried ${tried.map((t) => t.pathname).join(", ")})`,
          );
        }),
      );
      return `export const globalCss = ${JSON.stringify(sheets.join("\n"))};`;
    },
  };
}

async function writeRenderers(frameworks) {
  const sorted = [...frameworks].sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b));
  const lines = [
    "// GENERATED by scripts/build-editor.mjs from nocms.config.mjs — do not edit.",
    ...sorted.map((f, i) => `import r${i} from "@astrojs/${f}/server.js";`),
    "",
    "export const renderers = [",
    ...sorted.map(
      (f, i) =>
        `  { name: "@astrojs/${f}", server: r${i}, client: "@astrojs/${f}/client.js" },`,
    ),
    "];",
    "",
  ];
  await writeFile(
    fileURLToPath(new URL("../editor/renderers.mjs", import.meta.url)),
    lines.join("\n"),
  );
}

const root = fileURLToPath(new URL("../", import.meta.url));
const config = await import(new URL("../nocms.config.mjs", import.meta.url).href);
const frameworks = await declaredFrameworks(import.meta.url);
await writeRenderers(frameworks);

/**
 * The editor is built as an SSR bundle that runs in a browser.
 *
 * This is the load-bearing trick: an SSR build makes every framework plugin emit
 * SSR codegen, exactly as Astro's own server build does. A plain client build
 * silently produces DOM code that cannot be rendered to a string.
 */
await build({
  root,
  logLevel: "warn",
  plugins: [astroForEditor({ root }), shimPlugin(frameworks), declaredStyles(root)],
  define: { "process.env.NODE_ENV": '"production"' },
  // Component libraries ship .tsx/.jsx; the editor must compile them as the site does.
  esbuild: { jsx: "automatic" },
  resolve: {
    alias: [
      // react-dom/server resolves to the Node build; the browser build is the one
      // that works here, and it is roughly half the size.
      { find: /^react-dom\/server$/, replacement: "react-dom/server.browser" },
      { find: /^react-dom\/server\.js$/, replacement: "react-dom/server.browser" },
      {
        find: /^node:async_hooks$/,
        replacement: fileURLToPath(new URL("./async-hooks-shim.mjs", import.meta.url)),
      },
    ],
  },
  ssr: { noExternal: true, target: "webworker" },
  build: {
    ssr: fileURLToPath(new URL("../editor/main.mjs", import.meta.url)),
    outDir: ".nocms-build",
    emptyOutDir: true,
    minify: true,
    target: "es2022",
    rollupOptions: { output: { entryFileNames: "editor.js", format: "es" } },
  },
});

// The compiler is WASM in the browser; ship it next to the editor.
import { copyFile, mkdir, rm } from "node:fs/promises";

const out = fileURLToPath(new URL("../public/_nocms/", import.meta.url));
await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await copyFile(
  fileURLToPath(new URL("../.nocms-build/editor.js", import.meta.url)),
  `${out}editor.js`,
);
await copyFile(
  fileURLToPath(
    new URL("../node_modules/@astrojs/compiler/dist/astro.wasm", import.meta.url),
  ),
  `${out}astro.wasm`,
);
await rm(fileURLToPath(new URL("../.nocms-build", import.meta.url)), {
  recursive: true,
  force: true,
});
console.log("editor built -> public/_nocms/editor.js (+ astro.wasm)");
